# Generated by Django 4.1.7 on 2023-04-21 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('3', 'Шеф-инженер 3-й категории'), ('2', 'Шеф-инженер 2-й категории'), ('1', 'Шеф-инженер 1-й категории'), ('ld', 'Ведущий шеф-инженер')], default='ld', max_length=5)),
                ('start_date', models.DateField(help_text='Дата приёма')),
                ('end_date', models.DateField(blank=True, help_text='Дата увольнения', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfnumber', models.IntegerField(blank=True, help_text='Заводской номер', null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Количество', null=True)),
                ('factory', models.CharField(blank=True, help_text='Изготовитель', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Irrelevant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, help_text='Количество', null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Mismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' Краткое описание', max_length=400)),
                ('text', models.TextField(help_text=' Полное описание')),
                ('type', models.CharField(choices=[('p', 'Конструкторское'), ('m', 'Производстенное')], max_length=2)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/mismatch/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/mismatch/images/')),
                ('details', models.ManyToManyField(through='supervision.Irrelevant', to='supervision.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объекта', max_length=250, verbose_name='Модель оборудования (котла)')),
                ('equipment', models.CharField(blank=True, help_text='Модель оборудования (котла)', max_length=250, null=True, verbose_name='Модель оборудования (котла)')),
                ('equipment_type', models.CharField(blank=True, help_text='Тип оборудования (котла)', max_length=250, null=True, verbose_name='Тип оборудования (котла)')),
                ('contract', models.CharField(blank=True, help_text='номер договора', max_length=250, null=True, verbose_name='номер договора')),
                ('project_manager', models.CharField(blank=True, help_text='руководитель проекта', max_length=100, null=True, verbose_name='руководитель проекта')),
                ('chief_engineer', models.CharField(blank=True, help_text='главный инженер проекта', max_length=100, null=True, verbose_name='главный инженер проекта')),
                ('status', models.CharField(choices=[('prs', 'Перспективный'), ('act', 'Действующий'), ('cnc', 'Завершенный'), ('dlt', 'Отмененный')], default='prs', max_length=3, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Статус', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='номер узла без родителя')),
                ('suffix', models.CharField(blank=True, help_text='суфикс номера', max_length=10, null=True)),
                ('name', models.CharField(help_text='наименование узла/подузла', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_status', models.DateField(auto_now_add=True)),
                ('mismatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.status')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('to', models.CharField(blank=True, max_length=350, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/mismatch/solution/')),
                ('mismatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, help_text='Отчество', max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mismatch',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.place'),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(blank=True, null=True)),
                ('to', models.CharField(blank=True, max_length=350, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/mismatch/letter/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/mismatch/letter/images/')),
                ('mismatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='irrelevant',
            name='mismatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.mismatch'),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Обозначение детали', max_length=50)),
                ('name', models.CharField(help_text='Наименование детали', max_length=250)),
                ('order', models.IntegerField(blank=True, help_text='Номер Заказа', null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=3, help_text='Масса', max_digits=11, null=True)),
                ('steel', models.CharField(blank=True, help_text='Марка стали', max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/detail/')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.group')),
            ],
            options={
                'unique_together': {('number', 'name')},
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.drawing'),
        ),
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, help_text='Дата начала командировки', null=True, verbose_name='дата начала')),
                ('end', models.DateField(blank=True, help_text='Дата окончания командировки', null=True, verbose_name='дата окончания')),
                ('purpose', models.CharField(help_text='Цель командировки', max_length=250, verbose_name='Цель')),
                ('activ', models.BooleanField(default=False, help_text='Действующая', verbose_name='статус')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.place', verbose_name='Оъект')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'permissions': (('can_extension', 'Может продливать командировку'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='irrelevant',
            unique_together={('mismatch', 'detail')},
        ),
    ]
