# Generated by Django 4.1.7 on 2023-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объекта', max_length=250)),
                ('object_model', models.CharField(blank=True, help_text='Модель оборудования (котла)', max_length=250, null=True)),
                ('object_type', models.CharField(blank=True, help_text='Тип оборудования (котла)', max_length=250, null=True)),
                ('contract', models.CharField(blank=True, help_text='номер договора', max_length=250, null=True)),
                ('project_manager', models.CharField(blank=True, help_text='руководитель проекта', max_length=100, null=True)),
                ('chief_engineer', models.CharField(blank=True, help_text='главный инженер проекта', max_length=100, null=True)),
                ('status', models.CharField(choices=[('p', 'Перспективный'), ('a', 'Действующий'), ('c', 'Завершенный'), ('d', 'Отмененный')], default='a', max_length=2)),
            ],
        ),
    ]
