# Generated by Django 4.1.7 on 2023-04-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='unit',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='order',
        ),
        migrations.AddField(
            model_name='group',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.place', verbose_name='Оъект'),
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.IntegerField(blank=True, help_text='Номер Заказа', null=True),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='type',
            field=models.CharField(choices=[('p', 'Конструкторское'), ('m', 'Производстенное')], help_text='Тип несоответствия', max_length=2),
        ),
    ]
