# Generated by Django 4.1.7 on 2023-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='Статус', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='typemismatch',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Тип несоответствия'),
        ),
    ]
