# Generated by Django 4.1.7 on 2023-04-28 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0002_alter_position_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='activ',
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='purpose',
            field=models.CharField(max_length=250, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='factory',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='mfnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/detail/', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='mass',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=11, null=True, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование детали'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Обозначение детали'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='steel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Марка стали'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='наименование Группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveIntegerField(verbose_name='номер Группы, без номера родителя'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.group', verbose_name='Родительская Группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='суфикс Группы'),
        ),
        migrations.AlterField(
            model_name='irrelevant',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/mismatch/letter/', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/mismatch/letter/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mismatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch', verbose_name='Несоответствие'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/mismatch/', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/mismatch/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='text',
            field=models.TextField(verbose_name=' Полное описание'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='title',
            field=models.CharField(max_length=400, verbose_name=' Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='chief_engineer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='главный инженер проекта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='contract',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='номер договора'),
        ),
        migrations.AlterField(
            model_name='place',
            name='equipment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Модель оборудования (котла)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип оборудования (котла)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер Заказа'),
        ),
        migrations.AlterField(
            model_name='place',
            name='project_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/mismatch/solution/', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='mismatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch', verbose_name='Несоответствие'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер Тех.решения'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='to',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Статус'),
        ),
    ]
