# Generated by Django 4.1.7 on 2023-04-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0002_career_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(help_text='Дата начала командировки')),
                ('end', models.DateField(help_text='Дата окончания командировки')),
                ('purpose', models.CharField(help_text='Цель командировки', max_length=250)),
                ('object_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.objects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
