# Generated by Django 4.1.7 on 2023-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_remove_businesstrip_activ_alter_businesstrip_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='status',
            field=models.CharField(choices=[('perspective', 'Перспективный'), ('activ', 'Действующий'), ('canseled', 'Отмененный'), ('comleted', 'Завершенный')], default='perspective', max_length=20, verbose_name='статус'),
        ),
    ]
