# Generated by Django 4.1.7 on 2023-04-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Обозначение детали', max_length=50)),
                ('name', models.CharField(help_text='Наименование детали', max_length=250)),
                ('mass', models.DecimalField(blank=True, decimal_places=3, help_text='масса', max_digits=11, null=True)),
                ('steel', models.CharField(help_text='Марка стали', max_length=250)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.unit')),
            ],
        ),
    ]
