# Generated by Django 4.1.7 on 2023-04-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_position_alter_career_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('user', 'position')},
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(through='supervision.Career', to='supervision.position'),
        ),
    ]
