# Generated by Django 4.1.7 on 2023-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_businesstrip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstrip',
            name='status',
        ),
        migrations.AlterField(
            model_name='placestatus',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='статус объекта'),
        ),
    ]
