# Generated by Django 4.1.7 on 2023-04-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_alter_career_user_remove_profile_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='статус объекта')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.placestatus', verbose_name='Статус'),
        ),
    ]
