# Generated by Django 4.1.7 on 2023-04-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_remove_businesstrip_status_alter_placestatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Состояние командировки')),
            ],
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='purpose',
            field=models.CharField(max_length=250, verbose_name='Цель командировки'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.conditiontrip', verbose_name='статус'),
        ),
    ]
