# Generated by Django 4.1.7 on 2023-04-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0006_conditiontrip_alter_businesstrip_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_liner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cотрудник'),
        ),
    ]
