# Generated by Django 4.1.7 on 2023-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0007_profile_is_liner_alter_businesstrip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mismatch',
            name='correct',
            field=models.TextField(blank=True, null=True, verbose_name='Предложения по устранению'),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='status',
            field=models.ManyToManyField(through='supervision.Tracking', to='supervision.status'),
        ),
    ]
