# Generated by Django 4.1.7 on 2023-04-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0007_alter_profile_birth_date_alter_profile_position_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
