# Generated by Django 4.1.7 on 2023-05-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0008_mismatch_correct_mismatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrelevant',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.drawing'),
        ),
        migrations.AlterField(
            model_name='irrelevant',
            name='mismatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervision.mismatch'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='details',
            field=models.ManyToManyField(through='supervision.Irrelevant', to='supervision.drawing'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
