# Generated by Django 4.1.7 on 2023-05-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0009_alter_irrelevant_detail_alter_irrelevant_mismatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mismatch',
            name='details',
            field=models.ManyToManyField(through='supervision.Irrelevant', to='supervision.drawing', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.place', verbose_name='Объект'),
        ),
        migrations.RemoveField(
            model_name='mismatch',
            name='status',
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.typemismatch', verbose_name='Тип несоответствия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_liner',
            field=models.BooleanField(default=True, verbose_name='Если линейный специалист'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
        migrations.AddField(
            model_name='mismatch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.status', verbose_name='Статус несоответствия'),
        ),
    ]
