# Generated by Django 4.1.7 on 2023-05-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0010_alter_mismatch_details_alter_mismatch_place_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='irrelevant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='irrelevant',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='irrelevant',
            name='mismatch',
        ),
        migrations.RemoveField(
            model_name='mismatch',
            name='details',
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
        migrations.DeleteModel(
            name='Irrelevant',
        ),
    ]
