# Generated by Django 4.1.7 on 2023-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0010_alter_unit_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='наименование узла/подузла', max_length=200),
        ),
    ]
