# Generated by Django 4.1.7 on 2023-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0011_alter_irrelevant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mismatch',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали'),
        ),
    ]
