# Generated by Django 4.1.7 on 2023-04-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0012_alter_element_steel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together={('number', 'name')},
        ),
    ]
