# Generated by Django 4.1.7 on 2023-05-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0012_mismatch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.typemismatch', verbose_name='Тип несоответствия'),
        ),
    ]
