# Generated by Django 4.1.7 on 2023-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0013_alter_element_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(choices=[('3', '3 категория'), ('2', '2 категория'), ('1', '2 категория'), ('ld', 'Ведущий')], default='ld', max_length=5),
        ),
    ]
