# Generated by Django 4.1.7 on 2023-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0013_profile_photo_alter_mismatch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supervision/users/photo', verbose_name='Фото'),
        ),
    ]
