# Generated by Django 4.1.7 on 2023-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0014_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mismatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/mismatch/file', verbose_name='Файлы'),
        ),
    ]
