# Generated by Django 4.1.7 on 2023-04-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0015_alter_career_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mismatch',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='element',
            name='fac_number',
            field=models.IntegerField(blank=True, help_text='Заводской номер', null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='order',
            field=models.IntegerField(blank=True, help_text='Номер Заказа', null=True),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Количество', null=True),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='corrected',
            field=models.CharField(blank=True, help_text='Кем устранено', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='factory',
            field=models.CharField(blank=True, help_text='Изготовитель', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/mismatch/'),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/mismatch/images/'),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='pack',
            field=models.CharField(blank=True, help_text='Грузовое место', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mismatch',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.unit'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='end',
            field=models.DateField(blank=True, help_text='Дата окончания командировки', null=True),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='start',
            field=models.DateField(blank=True, help_text='Дата начала командировки', null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(choices=[('3', '3 категория'), ('2', '2 категория'), ('1', '1 категория'), ('ld', 'Ведущий')], default='ld', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='mass',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Масса', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='answer',
            field=models.CharField(blank=True, help_text='Ответ служебное письмо', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='date_finding',
            field=models.DateField(blank=True, help_text='Дата', null=True),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='letter',
            field=models.CharField(blank=True, help_text='Номер служебного письма', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='solution',
            field=models.CharField(blank=True, help_text='Принятое решени', max_length=150, null=True),
        ),
    ]
