# Generated by Django 4.1.7 on 2023-04-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0016_rename_name_mismatch_title_element_fac_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Статус', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_status', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/mismatch/status/')),
                ('mismatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.mismatch')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.status')),
            ],
        ),
        migrations.AddField(
            model_name='mismatch',
            name='status',
            field=models.ManyToManyField(through='supervision.Tracking', to='supervision.status'),
        ),
    ]
