# Generated by Django 4.1.7 on 2023-04-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0017_status_tracking_mismatch_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracking',
            unique_together={('mismatch', 'status')},
        ),
    ]
