# Generated by Django 4.1.7 on 2023-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0017_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mismatch',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mismatch/file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='mismatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mismatch/images/', verbose_name='Фото'),
        ),
    ]
