# Generated by Django 4.1.7 on 2023-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0019_alter_tracking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='status',
            field=models.BooleanField(default=True, help_text='Действующая, Завершенная'),
        ),
    ]
