# Generated by Django 4.1.7 on 2023-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0020_businesstrip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='status',
            new_name='activ',
        ),
    ]
