# Generated by Django 4.1.7 on 2023-06-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0020_drawing_irrelevant_mismatch_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250, verbose_name='Материал')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drawing',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.description', verbose_name='Наименование детали'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.material', verbose_name='Материал'),
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together={('number', 'description')},
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='steel',
        ),
    ]
