# Generated by Django 4.1.7 on 2023-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0021_description_material_alter_drawing_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='gost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ГОСТ'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('material', 'gost')},
        ),
    ]
