# Generated by Django 4.1.7 on 2023-04-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0022_plaсe_remove_businesstrip_object_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='activ',
            field=models.BooleanField(default=False, help_text='Действующая'),
        ),
    ]
