# Generated by Django 4.1.7 on 2023-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0022_material_gost_alter_material_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['material']},
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=250, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='material',
            name='gost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ГОСТ/ТУ'),
        ),
    ]
