# Generated by Django 4.1.7 on 2023-04-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0023_alter_businesstrip_activ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstrip',
            options={'permissions': (('can_extension', 'Может продливать командировку'),)},
        ),
    ]
