# Generated by Django 4.1.7 on 2023-06-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0023_alter_description_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.material', verbose_name='Материал'),
        ),
    ]
