# Generated by Django 4.1.7 on 2023-04-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervision', '0024_alter_businesstrip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='activ',
            field=models.BooleanField(default=False, help_text='Действующая', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='end',
            field=models.DateField(blank=True, help_text='Дата окончания командировки', null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='plaсe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.plaсe', verbose_name='Оъект'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='purpose',
            field=models.CharField(help_text='Цель командировки', max_length=250, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='start',
            field=models.DateField(blank=True, help_text='Дата начала командировки', null=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(choices=[('3', 'Шеф-инженер 3-й категории'), ('2', 'Шеф-инженер 2-й категории'), ('1', 'Шеф-инженер 1-й категории'), ('ld', 'Ведущий шеф-инженер')], default='ld', max_length=5),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='chief_engineer',
            field=models.CharField(blank=True, help_text='главный инженер проекта', max_length=100, null=True, verbose_name='главный инженер проекта'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='contract',
            field=models.CharField(blank=True, help_text='номер договора', max_length=250, null=True, verbose_name='номер договора'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='equipment',
            field=models.CharField(blank=True, help_text='Модель оборудования (котла)', max_length=250, null=True, verbose_name='Модель оборудования (котла)'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='equipment_type',
            field=models.CharField(blank=True, help_text='Тип оборудования (котла)', max_length=250, null=True, verbose_name='Тип оборудования (котла)'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='name',
            field=models.CharField(help_text='Название объекта', max_length=250, verbose_name='Модель оборудования (котла)'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='project_manager',
            field=models.CharField(blank=True, help_text='руководитель проекта', max_length=100, null=True, verbose_name='руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='plaсe',
            name='status',
            field=models.CharField(choices=[('p', 'Перспективный'), ('a', 'Действующий'), ('c', 'Завершенный'), ('d', 'Отмененный')], default='a', max_length=2, verbose_name='Статус'),
        ),
    ]
