# Generated by Django 4.1.7 on 2023-06-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0024_alter_drawing_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='chief_engineer',
        ),
        migrations.RemoveField(
            model_name='place',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='place',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='place',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='order',
        ),
        migrations.RemoveField(
            model_name='place',
            name='project_manager',
        ),
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер Заказа')),
                ('contract', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер Договора')),
                ('boiler', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Станционный номер Котла')),
                ('equipment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Модель оборудования (котла)')),
                ('equipment_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип оборудования (котла)')),
                ('project_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='руководитель проекта')),
                ('chief_engineer', models.CharField(blank=True, max_length=100, null=True, verbose_name='главный инженер проекта')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.place', verbose_name='Объект')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervision.placestatus', verbose_name='Статус Заказа')),
            ],
        ),
    ]
