# Generated by Django 4.1.7 on 2023-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0025_remove_place_chief_engineer_remove_place_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название объекта'),
        ),
    ]
