# Generated by Django 4.1.7 on 2023-04-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0025_profile_death_date_alter_businesstrip_activ_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plaсe',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='businesstrip',
            old_name='plaсe',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='mismatch',
            old_name='plaсe',
            new_name='place',
        ),
    ]
